
export const BASIC_TEMPLATE: Record<string, string> = {
  'package.json': JSON.stringify({
    name: "helios-project",
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      "dev": "helios studio",
      "build": "tsc && vite build",
      "render": "helios render"
    },
    dependencies: {
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "@helios-project/core": "^5.10.0"
    },
    devDependencies: {
      "@types/react": "^18.2.66",
      "@types/react-dom": "^18.2.22",
      "@vitejs/plugin-react": "^4.2.1",
      "typescript": "^5.2.2",
      "vite": "^5.2.0",
      "@helios-project/cli": "latest"
    }
  }, null, 2),

  'vite.config.ts': `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
})
`,

  'tsconfig.json': JSON.stringify({
    "compilerOptions": {
      "target": "ES2020",
      "useDefineForClassFields": true,
      "lib": ["ES2020", "DOM", "DOM.Iterable"],
      "module": "ESNext",
      "skipLibCheck": true,
      "moduleResolution": "bundler",
      "allowImportingTsExtensions": true,
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "react-jsx",
      "strict": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noFallthroughCasesInSwitch": true
    },
    "include": ["src"]
  }, null, 2),

  'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Helios Project</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/index.tsx"></script>
  </body>
</html>
`,

  '.gitignore': `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# Helios
.helios/
output.mp4
`,

  'src/vite-env.d.ts': `/// <reference types="vite/client" />
`,

  'src/helios.ts': `import { Helios } from '@helios-project/core';

export const helios = new Helios({
  fps: 30,
  duration: 5 // seconds
});

// Bind to document timeline (allows Helios to control the animation)
helios.bindToDocumentTimeline();
`,

  'src/index.tsx': `import React from 'react'
import ReactDOM from 'react-dom/client'
import './helios' // Initialize Helios
import HelloWorld from './components/HelloWorld'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <HelloWorld />
  </React.StrictMode>,
)
`,

  'src/components/HelloWorld.tsx': `import React, { useEffect, useRef } from 'react';
import { helios } from '../helios';

export default function HelloWorld() {
  const ref = useRef<HTMLHeadingElement>(null);

  useEffect(() => {
    // Subscribe to Helios frame updates
    const unsubscribe = helios.subscribe((state) => {
      if (ref.current) {
        // Example: Animate opacity based on time
        // state.currentTime is the current time in seconds
        const opacity = Math.min(state.currentTime, 1);
        ref.current.style.opacity = opacity.toString();
        ref.current.style.transform = \`translateY(\${(1 - opacity) * 20}px)\`;
      }
    });

    return unsubscribe;
  }, []);

  return (
    <div style={{
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100vh',
      fontFamily: 'sans-serif',
      backgroundColor: '#1a1a1a',
      color: '#fff'
    }}>
      <h1 ref={ref}>Hello Helios!</h1>
    </div>
  );
}
`
};
