
export const SOLID_TEMPLATE: Record<string, string> = {
  'package.json': JSON.stringify({
    name: "helios-project",
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      "dev": "helios studio",
      "build": "tsc && vite build",
      "render": "helios render"
    },
    dependencies: {
      "solid-js": "^1.9.11",
      "@helios-project/core": "^5.11.0"
    },
    devDependencies: {
      "typescript": "^5.0.0",
      "vite": "^7.1.2",
      "vite-plugin-solid": "^2.11.10",
      "@helios-project/cli": "latest"
    }
  }, null, 2),

  'vite.config.ts': `import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

export default defineConfig({
  plugins: [solidPlugin()],
});
`,

  'tsconfig.json': JSON.stringify({
    "compilerOptions": {
      "target": "ESNext",
      "useDefineForClassFields": true,
      "module": "ESNext",
      "lib": ["ESNext", "DOM"],
      "moduleResolution": "Node",
      "strict": true,
      "sourceMap": true,
      "resolveJsonModule": true,
      "isolatedModules": true,
      "esModuleInterop": true,
      "noEmit": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noImplicitReturns": true,
      "skipLibCheck": true,
      "jsx": "preserve",
      "jsxImportSource": "solid-js"
    },
    "include": ["src"]
  }, null, 2),

  'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Helios Project</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/index.tsx"></script>
  </body>
</html>
`,

  '.gitignore': `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# Helios
.helios/
output.mp4
`,

  'src/vite-env.d.ts': `/// <reference types="vite/client" />
`,

  'src/helios.ts': `import { Helios } from '@helios-project/core';

export const helios = new Helios({
  fps: 30,
  duration: 5 // seconds
});

// Bind to document timeline (allows Helios to control the animation)
helios.bindToDocumentTimeline();
`,

  'src/index.tsx': `/* @refresh reload */
import { render } from 'solid-js/web';
import './helios'; // Initialize Helios

import App from './App';

const root = document.getElementById('root');

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?',
  );
}

render(() => <App />, root!);
`,

  'src/App.tsx': `import { createMemo, Component } from 'solid-js';
import { createHeliosSignal } from './lib/createHeliosSignal';
import { helios } from './helios';

const App: Component = () => {
  const state = createHeliosSignal(helios);

  const rotation = createMemo(() => {
    const s = state();
    const totalFrames = s.duration * helios.fps;
    const progress = totalFrames > 0 ? s.currentFrame / totalFrames : 0;
    return progress * 360;
  });

  return (
    <div style={{
      display: 'flex',
      "justify-content": 'center',
      "align-items": 'center',
      height: '100vh',
      "font-family": 'sans-serif',
      "background-color": '#1a1a1a',
      color: '#fff',
      "flex-direction": 'column',
      gap: '20px'
    }}>
      <h1>Hello Helios + Solid!</h1>
      <div style={{
        width: '100px',
        height: '100px',
        "background-color": '#446b9e',
        "border-radius": '8px',
        display: 'flex',
        "justify-content": 'center',
        "align-items": 'center',
        transform: \`rotate(\${rotation()}deg)\`
      }}>
        Box
      </div>
    </div>
  );
};

export default App;
`,

  'src/lib/createHeliosSignal.ts': `import { createSignal, onCleanup, onMount } from 'solid-js';
import { Helios } from '@helios-project/core';

export function createHeliosSignal(helios: Helios) {
  const [state, setState] = createSignal(helios.getState());

  onMount(() => {
    const unsub = helios.subscribe(setState);
    onCleanup(() => {
      unsub();
    });
  });

  return state;
}
`
};
