
export const SVELTE_TEMPLATE: Record<string, string> = {
  'package.json': JSON.stringify({
    name: "helios-project",
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      "dev": "helios studio",
      "build": "vite build && svelte-check",
      "check": "svelte-check --tsconfig ./tsconfig.json",
      "render": "helios render"
    },
    dependencies: {
      "svelte": "^5.48.2",
      "@helios-project/core": "^5.11.0"
    },
    devDependencies: {
      "@sveltejs/vite-plugin-svelte": "^6.2.4",
      "@tsconfig/svelte": "^5.0.0",
      "svelte-check": "^4.0.0",
      "tslib": "^2.6.0",
      "typescript": "^5.2.2",
      "vite": "^7.1.2",
      "@helios-project/cli": "latest"
    }
  }, null, 2),

  'vite.config.ts': `import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()],
})
`,

  'tsconfig.json': JSON.stringify({
    "extends": "@tsconfig/svelte/tsconfig.json",
    "compilerOptions": {
      "target": "ESNext",
      "useDefineForClassFields": true,
      "module": "ESNext",
      "resolveJsonModule": true,
      "allowJs": true,
      "checkJs": true,
      "isolatedModules": true
    },
    "include": ["src/**/*.d.ts", "src/**/*.ts", "src/**/*.js", "src/**/*.svelte"]
  }, null, 2),

  'svelte.config.js': `import { vitePreprocess } from '@sveltejs/vite-plugin-svelte'

export default {
  // Consult https://svelte.dev/docs#compile-time-svelte-preprocess
  // for more information about preprocessors
  preprocess: vitePreprocess(),
}
`,

  'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Helios Project</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`,

  '.gitignore': `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# Helios
.helios/
output.mp4
`,

  'src/vite-env.d.ts': `/// <reference types="svelte" />
/// <reference types="vite/client" />
`,

  'src/helios.ts': `import { Helios } from '@helios-project/core';

export const helios = new Helios({
  fps: 30,
  duration: 5 // seconds
});

// Bind to document timeline (allows Helios to control the animation)
helios.bindToDocumentTimeline();
`,

  'src/main.ts': `import { mount } from 'svelte'
import './helios' // Initialize Helios
import App from './App.svelte'

const app = mount(App, {
  target: document.getElementById('app')!,
})

export default app
`,

  'src/App.svelte': `<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { helios } from './helios';

  let opacity = 0;
  let translation = 0;
  let unsubscribe: () => void;

  onMount(() => {
    unsubscribe = helios.subscribe((state) => {
      opacity = Math.min(state.currentTime, 1);
      translation = (1 - opacity) * 20;
    });
  });

  onDestroy(() => {
    if (unsubscribe) unsubscribe();
  });
</script>

<div class="container">
  <h1 style:opacity={opacity} style:transform={\`translateY(\${translation}px)\`}>
    Hello Helios!
  </h1>
</div>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
  }
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    font-family: sans-serif;
    background-color: #1a1a1a;
    color: #fff;
  }
</style>
`
};
