
export const VUE_TEMPLATE: Record<string, string> = {
  'package.json': JSON.stringify({
    name: "helios-project",
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      "dev": "helios studio",
      "build": "vue-tsc && vite build",
      "render": "helios render"
    },
    dependencies: {
      "vue": "^3.5.27",
      "@helios-project/core": "^5.11.0"
    },
    devDependencies: {
      "@vitejs/plugin-vue": "^6.0.3",
      "typescript": "^5.2.2",
      "vite": "^7.1.2",
      "vue-tsc": "^2.0.0",
      "@helios-project/cli": "latest"
    }
  }, null, 2),

  'vite.config.ts': `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
})
`,

  'tsconfig.json': JSON.stringify({
    "compilerOptions": {
      "target": "ES2020",
      "useDefineForClassFields": true,
      "module": "ESNext",
      "lib": ["ES2020", "DOM", "DOM.Iterable"],
      "skipLibCheck": true,

      /* Bundler mode */
      "moduleResolution": "bundler",
      "allowImportingTsExtensions": true,
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "preserve",

      /* Linting */
      "strict": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noFallthroughCasesInSwitch": true
    },
    "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
  }, null, 2),

  'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Helios Project</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`,

  '.gitignore': `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# Helios
.helios/
output.mp4
`,

  'src/vite-env.d.ts': `/// <reference types="vite/client" />
`,

  'src/helios.ts': `import { Helios } from '@helios-project/core';

export const helios = new Helios({
  fps: 30,
  duration: 5 // seconds
});

// Bind to document timeline (allows Helios to control the animation)
helios.bindToDocumentTimeline();
`,

  'src/main.ts': `import { createApp } from 'vue'
import './helios' // Initialize Helios
import App from './App.vue'

createApp(App).mount('#app')
`,

  'src/App.vue': `<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { helios } from './helios';

const opacity = ref(0);
const translation = ref(0);

// Subscribe to Helios updates
const unsubscribe = helios.subscribe((state) => {
  opacity.value = Math.min(state.currentTime, 1);
  translation.value = (1 - opacity.value) * 20;
});

onUnmounted(() => {
  unsubscribe();
});
</script>

<template>
  <div class="container">
    <h1 :style="{ opacity: opacity, transform: \`translateY(\${translation}px)\` }">
      Hello Helios!
    </h1>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-family: sans-serif;
  background-color: #1a1a1a;
  color: #fff;
}
</style>
`
};
